version: "3.7"
services:
  app:
    build:
      args:        
        php_version: ${PHP_VERSION}        
      context: ./
      dockerfile: Dockerfile
    image: dockerphp
    container_name: ximdex-php
    restart: unless-stopped
    working_dir: /app
    volumes:
      - ./app:/app
    networks:
      - dockerphp

  nginx:
    image: nginx:alpine
    container_name: ximdex-nginx
    restart: unless-stopped
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - ./app:/app
      - ./docker-compose/nginx:/etc/nginx/conf.d
    networks:
      - dockerphp

networks:
  dockerphp:
    driver: bridge
